#!/bin/bash

# /etc/libvirt/hooks/qemu

# https://wiki.libvirt.org/page/Networking#Forwarding_Incoming_Connections

# IMPORTANT: Change the "VM NAME" string to match your actual VM Name.
# In order to create rules to other VMs, just duplicate the below block and configure
# it accordingly.

# ubuntu-server
if [ "${1}" = "ubuntu-server" ]; then

   # Update the following variables to fit your setup
   GUEST_IP=192.168.122.100
   #GUEST_PORT=80
   GUEST_PORT_HTTP=80
   GUEST_PORT_HTTPS=443
   GUEST_PORT_COCKPIT=9090
   #HOST_PORT=8080
   HOST_PORT_HTTP=8080
   HOST_PORT_COCKPIT=9090

   if [ "${2}" = "stopped" ] || [ "${2}" = "reconnect" ]; then
        /sbin/iptables -D FORWARD -o virbr0 -d  $GUEST_IP -j ACCEPT
        /sbin/iptables -t nat -D PREROUTING -p tcp --dport $HOST_PORT_HTTP -j DNAT --to $GUEST_IP:$GUEST_PORT_HTTP
        /sbin/iptables -t nat -D PREROUTING -p tcp --dport $HOST_PORT_COCKPIT -j DNAT --to $GUEST_IP:$GUEST_PORT_COCKPIT
   fi
   if [ "${2}" = "start" ] || [ "${2}" = "reconnect" ]; then
        /sbin/iptables -I FORWARD -o virbr0 -d  $GUEST_IP -j ACCEPT
        /sbin/iptables -t nat -I PREROUTING -p tcp --dport $HOST_PORT_HTTP -j DNAT --to $GUEST_IP:$GUEST_PORT_HTTP
        /sbin/iptables -t nat -I PREROUTING -p tcp --dport $HOST_PORT_COCKPIT -j DNAT --to $GUEST_IP:$GUEST_PORT_COCKPIT
   fi
fi
